version: '3'
services:
  merms-panel:
    # image: registry.chiefsoft.net/wrenchboard-users-wrench:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - NODE_ENV=development
    restart: unless-stopped
    ports:
      - 8090:3000
    # stdin_open: true
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - ./src/:/usr/src/app/src
      - ./run.sh:/usr/src/app/run.sh
      - ./node_modules/:/usr/src/app/node_modules
    extra_hosts:
      - api.mermsemr.com:10.10.33.15
      - devapi.mermsemr.com:10.10.33.15
      - dev-socket.mermsemr.com:10.10.33.15
      - socket.mermsemr.com:10.10.33.15
      - dev-media.mermsemr.com:10.10.33.15
      - media.mermsemr.com:10.10.33.15
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=${NODE_ENV:-production}
    tty: true
    stdin_open: true
    # working_dir: /app
volumes:
  src:
